---
- hosts: apibackend
  gather_facts: false
  become: true
  collections:
    - community.docker
  vars:
    nome: 'backend'
    versao: 'v01'
  tasks:

  - ansible.builtin.copy:
      dest: /etc/profile.d/00-bash-proxy.sh
      mode: '0644'
      content: |
        export http_proxy="http://proxy:3128"
        export https_proxy="http://proxy:3128"
        export ftp_proxy="http://proxy:3128"

  - ansible.builtin.lineinfile:
      path: /etc/yum.conf
      state: present
      line: 'proxy=http://proxy:3128'

  - ansible.builtin.file:
      path: /etc/systemd/system/docker.service.d
      owner: root
      group: root
      mode: '0755'
      state: directory

  - ansible.builtin.copy:
      dest: /etc/systemd/system/docker.service.d/http-proxy.conf
      content: |
        [Service]
        Environment=HTTP_PROXY=http://proxy:3128/ 

  - ansible.builtin.copy:
      dest: /etc/systemd/system/docker.service.d/https-proxy.conf
      content: |
        [Service]
        Environment=HTTPS_PROXY=http://proxy:3128/ 

  - ansible.builtin.systemd:
      daemon_reload: yes

  - ansible.builtin.get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  - ansible.builtin.dnf:
      name: 
        - docker-ce
        - python3-pip
        - python3-setuptools
        - httpd
      state: latest

  - ansible.builtin.pip:
        name:
          - docker

  - ansible.builtin.service:
      name: docker
      state: started
      enabled: yes

  - community.docker.docker_image:
      name: "{{ nome }}:{{ versao }}"
      build:
        path: 'dockerback/'
      source: build
      state: present

  - community.docker.docker_container:
      name: "{{ nome }}-{{ versao }}-prod"
      image: "{{ nome }}:{{ versao }}"
      state: started
      detach: yes
      tty: yes
      restart_policy: always
      ports:
        - "0.0.0.0:8080:8080"
        - "0.0.0.0:443:443"
      env:
        MYSQL_DB_HOST: "jdbc:mysql://mysqlbackend:3306"
        MYSQL_DB_USER: "backend"
        MYSQL_DB_PASS: "N4t5%a0&vPx2"