---
- hosts: apibackend
  gather_facts: false
  become: true
  collections:
    - community.docker
    - community.mysql
  vars:
    nome: 'backend'
    versao: 'v01'
    mysqlBackendSenha: 'N4t5%a0&vPx2'
    mysqlBackendUsuario: 'apibackend'
    mysqlBackendHost: 'mysqlbackend'
    mysqlBackendDb: 'letscodebyada'
  tasks:

  - ansible.builtin.get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  - ansible.builtin.dnf:
      name: 
        - docker-ce
        - python3-pip
        - python3-setuptools
        - python3-mysql
        - httpd
      state: latest

  - ansible.builtin.pip:
      name:
        - docker

  - ansible.builtin.service:
      name: docker
      state: started
      enabled: yes

  - ansible.builtin.copy:
      src: 'dockerback'
      dest: '/root/'

  - community.docker.docker_image:
      name: "{{ nome }}:{{ versao }}"
      build:
        path: '/root/dockerback'
      source: build
      state: present

  - community.docker.docker_container:
      name: "{{ nome }}-{{ versao }}-prod"
      image: "{{ nome }}:{{ versao }}"
      state: started
      detach: yes
      tty: yes
      restart_policy: always
      ports:
        - "0.0.0.0:8080:8080"
        - "0.0.0.0:443:443"
      env:
        MYSQL_DB_HOST: "jdbc:mysql://{{ mysqlBackendHost }}:3306"
        MYSQL_DB_USER: "{{ mysqlBackendUsuario }}"
        MYSQL_DB_PASS: "{{ mysqlBackendSenha }}"
  
  # ninguém viu isso :)
  - ansible.builtin.pause:
      seconds: 30

  - community.mysql.mysql_query:
      login_db: "{{ mysqlBackendDb }}"
      login_host: "{{ mysqlBackendHost }}"
      login_password: "{{ mysqlBackendSenha }}"
      login_user: "{{ mysqlBackendUsuario }}"
      query:
        - INSERT INTO usuario (password, username) VALUES ('letscodeiac', 'letscodeiac')