---
- hosts: localhost
  gather_facts: false
  collections:
    community.general
  vars:
    # - Projeto
    dominio: 'homolog.conexaoinfraestrutura.inf.br'
    ssh_chave: "aws-ec2-administrador.pem"
    awscli_perfil: 'conexinfra'
    # - Git
    git_repo: 'github.com/felipediefenbach/letscodeiac.git'
    git_proto: 'https'
    git_diretorio: '/srv/letscodeiac'
    git_branch: 'feature/kubernets'
    # - Registro/Imagens
    frontendNone: 'frontend'
    frontendVersao: 'latest'
    backendNone: 'backend'
    backendVersao: 'latest'
  tasks:

    - community.general.terraform:
        project_path: "./"
        state: present
      tags: [ never, terraform, criar ]

    - ansible.builtin.file:
        dest: './aws-ec2-administrador.pem'
        owner: root
        group: 'root'
        mode: '0600'
      tags: [ never, git, criar ]

    - ansible.builtin.file:
        dest: './ansible.cfg'
        owner: root
        group: 'root'
        mode: '0600'
      tags: [ never, git, criar ]

    - ansible.builtin.wait_for_connection:
      delegate_to: acesso.{{ dominio }}

    - ansible.builtin.dnf:
        name: epel-release
      delegate_to: acesso.{{ dominio }}
      become: true
      tags: [ never, git, criar ]

    - ansible.builtin.dnf:
        name:
          - git
          - ansible
        update_cache: true
      delegate_to: acesso.{{ dominio }}
      become: true
      tags: [ never, git, criar ]

    - ansible.builtin.git:
        repo: "{{ git_proto }}://{{ git_repo }}"
        dest: "{{ git_diretorio }}"
        version: "{{ git_branch }}"
        update: true
        force: true
      delegate_to: acesso.{{ dominio }}
      become: true
      tags: [ never, git, criar ]

    - ansible.builtin.copy:
        src: './aws-ec2-administrador.pem'
        dest: "{{ git_diretorio }}/aws-ec2-administrador.pem"
        owner: 'root'
        group: 'root'
        mode: '0600'
      delegate_to: acesso.{{ dominio }}
      become: true
      tags: [ never, git, criar ]

    # login no registro
    - ansible.builtin.shell: |
        aws --profile {{ awscli_perfil }} ecr get-login-password --region us-east-1 > /var/tmp/registro-login
      tags: [ never, registro, criar ]

    - ansible.builtin.shell: |
        terraform output urlRepoFrontend | tr -d '"' | cut -d '/' -f 1
      register: pega_repo_frontend
      tags: [ never, registro, criar ]

    - ansible.builtin.set_fact:
        registro: "{{ pega_repo_frontend.stdout }}"
      tags: [ never, registro, criar ]

    - ansible.builtin.shell: |
        cat /var/tmp/registro-login | docker login --username AWS --password-stdin {{ registro }}
      tags: [ never, registro, criar ]

    # push frontend
    - community.docker.docker_image:
        build:
          path: 'dockerfront/'
        name: "{{ registro }}/{{ frontendNone }}"
        tag: "{{ frontendVersao }}"
        push: true
        source: build
      tags: [ never, registro, criar ]

    # push do backend
    - community.docker.docker_image:
        build:
          path: 'dockerback/'
        name: "{{ registro }}/{{ backendNone }}"
        tag: "{{ backendVersao }}"
        push: true
        source: build
      tags: [ never, registro, criar ]

    - ansible.builtin.copy:
        src: '/var/tmp/registro-login'
        dest: "/var/tmp/registro-login"
        owner: 'root'
        group: 'root'
        mode: '0600'
      delegate_to: acesso.{{ dominio }}
      become: true
      tags: [ never, registro, criar ]

    - ansible.builtin.shell: |
        ansible-playbook frontend.yml
        ansible-playbook -i apibackend, backend.yml
      args:
        chdir: "{{ git_diretorio }}"
        executable: /bin/bash
      delegate_to: acesso.{{ dominio }}
      become: true
      tags: [ never, homolog, criar ]

    - community.general.terraform:
        project_path: "./"
        state: absent
      tags: [ never, destruir ]