---
- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.docker
  vars:
    nome: 'frontend'
    versao: 'v01'
  tasks:

  - ansible.builtin.dnf:
      name: epel-release
    state: latest

  - ansible.builtin.get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  - ansible.builtin.dnf:
      name: 
        - docker-ce
        - python3-pip
        - python3-setuptools
        - httpd
      state: latest

  - ansible.builtin.pip:
        name:
          - docker

  - ansible.builtin.service:
      name: docker
      state: started
      enabled: yes

  - community.docker.docker_image:
      name: "{{ nome }}:{{ versao }}"
      build:
        path: 'dockerfront/'
      source: build
      state: present

  - community.docker.docker_container:
      name: "{{ nome }}-{{ versao }}-prod"
      image: "{{ nome }}:{{ versao }}"
      state: started
      detach: yes
      tty: yes
      restart_policy: always
      ports:
        - "0.0.0.0:4200:4200"
  
  - ansible.builtin.copy:
      dest: '/etc/httpd/conf.d/proxy.conf'
      content: |
        <VirtualHost *:80>
          ErrorLog /var/log/httpd/app.err
          CustomLog /var/log/httpd/app.log combined

          ProxyPreserveHost On
          ProxyPass / http://172.17.0.1:4200/
          ProxyPassReverse / http://172.17.0.1:4200/
        </VirtualHost>

  - ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes