---
- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.docker
  vars:
    nome: 'frontend'
    versao: 'v01'
  tasks:

  - ansible.builtin.get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  - ansible.builtin.dnf:
      name: 
        - docker-ce
        -  python3-docker
      state: latest

  - ansible.builtin.service:
      name: docker
      state: started
      enabled: yes

  - community.docker.docker_image:
      name: "{{ nome }}:{{ versao }}"
      build:
        path: /root/dockerfile-frontend
      source: build
      state: present

  - community.docker.docker_container:
      name: "{{ nome }}-{{ versao }}-prod"
      image: "{{ nome }}:{{ versao }}"
      state: started
      detach: yes
      tty: yes
      restart_policy: always
      ports:
        - "0.0.0.0:4200:4200"