apiVersion: v1
kind: pod
metadata:
  name: letscodeiac
spec:
  containers:
  - name: frontend
    image: frontend:v1
    ports:
      - containerPort: 4200
  - name: backend
    image: backend:v1
    ports:
      - containerPort: 8080
    env:
    - name: MYSQL_DB_HOST
      value: "jdbc:mysql://mysqlbackend.adainterno:3306/letscodebyada"
    - name: MYSQL_DB_USER
      value: "apibackend"
    - name: MYSQL_DB_PASS
      value: "N4t5%a0&vPx2"

# MYSQL_DB_HOST: "jdbc:mysql://{{ mysqlBackendHost }}:3306/{{ mysqlBackendDb }}"
# MYSQL_DB_USER: "{{ mysqlBackendUsuario }}"
# MYSQL_DB_PASS: "{{ mysqlBackendSenha }}"
# mysqlBackendSenha: 'N4t5%a0&vPx2'
# mysqlBackendUsuario: 'apibackend'
# mysqlBackendHost: 'mysqlbackend'
# mysqlBackendDb: 'letscodebyada'