---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: hello
      tier: api
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
        tier: api
        track: stable
    spec:
      containers:
        - name: hello
          image: registry.adainterno/letscodeiac/backend:v01
          ports:
            - name: node
              containerPort: 4200