---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: hello
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: nginx
          image: "864342323788.dkr.ecr.us-east-1.amazonaws.com/frontend:latest"
          ports:
            - name: node
              containerPort: 4200
 
                    